Fix cisco.ios pipeline bug for syslog input (#12951) (#12955)
This fixes a problem with the pipeline when being used with the syslog input (rather than the files that we test with). The dissect processor tries to set a field that is already added by the syslog input.

    GoError: cannot override existing key with `event.severity`

(cherry picked from commit 259992f1c216e58a4f70e715023e70ec58c5ccd2)