fix packetbeat devices command (#6307) (#6311)
The -devices flag is not valid, it yields:

/usr/share/packetbeat/bin/packetbeat -devices
Error: unknown flag: --devices

The command is "packetbeat devices"

(cherry picked from commit 3db4ce39206a662d5ec419c6416939802a7f9769)