Fix broken generator tests, updates to go.sum needed (#25251) (#25270)
Both generator tests were failing because the go.sum needed an update after running `mage test`.
The tools.go file was not updated to include gotest.tools/gotestsum/cmd which is installed while
running `mage test`.

The original errors were:
    go: updates to go.sum needed, disabled by -mod=readonly
    Error: running "go build -o build/golang-crossbuild/testbeat-windows-amd64.exe -buildmode pie -ldflags -s -extldflags=-Wl,--nxcompat -X github.com/elastic/beats/v7/libbeat/version.buildTime=2021-04-22T20:49:55Z -X github.com/elastic/beats/v7/libbeat/version.commit=c3a7a6abdf2a15cfd685e82ce1fe502296509825" failed with exit code 1
    Error: failed building for windows/amd64: exit status 1
    failed building for windows/amd64: exit status 1

    go: updates to go.sum needed, disabled by -mod=readonly
    Error: running "go build -o build/golang-crossbuild/testbeat-windows-386.exe -buildmode pie -ldflags -s -extldflags=-Wl,--nxcompat -X github.com/elastic/beats/v7/libbeat/version.buildTime=2021-04-22T20:49:55Z -X github.com/elastic/beats/v7/libbeat/version.commit=c3a7a6abdf2a15cfd685e82ce1fe502296509825" failed with exit code 1
    Error: failed building for windows/386: exit status 1
    failed building for windows/386: exit status 1

(cherry picked from commit c67d1613398f849d4081d21687b45dba64ebbffe)

Co-authored-by: Andrew Kroh <andrew.kroh@elastic.co>